FleekHQ/fleek-docs

content/Troubleshooting.mdx
Added a tips by framework section for Hugo
=> tips by framework - hugo

docs/hosting/overview.md, docs/stylesheets/extra.css
- Modify preview box css
- Add missing info box
=> Style changes

docs/space-daemon/getting-started.md
- Updated docs space-daemon default bucket
=> Updated docs space-daemon default bucket

docs/space-daemon/getting-started.md
section about notificationSubscription
=> added section about notifications to client v0.2.0

docs/space-daemon/getting-started.md
- Added getNotifications method docs
=> Added getNotifications method docs

docs/space-daemon/getting-started.md
=> Added deleteKeyPair docs

docs/space-daemon/getting-started.md
- Added GetSharedWithMeFiles docs
=> Added GetSharedWithMeFiles docs

docs/space-daemon/getting-started.md
- Added getRecentlySharedWith docs
=> Added getRecentlySharedWith docs

docs/space-daemon/getting-started.md
- Added GeneratePublicFileLink docs
=> Added GeneratePublicFileLink docs

docs/space-daemon/getting-started.md
- Added ShareFilesViaPublicKey docs
=> Added ShareFilesViaPublicKey docs

docs/space-daemon/getting-started.md
- Updated `GeneratePublicFileLink` docs
- Updated `GetSharedWithMeFiles` docs
=> Updated GeneratePublicFileLink and GetSharedWithMeFiles

docs/space-daemon/getting-started.md
- Updated ShareFilesViaPublicKeyRequest docs
=> Updated ShareFilesViaPublicKeyRequest docs

docs/space-daemon/getting-started.md
=> Update openFile docs

docs/space-daemon/getting-started.md
=> Added searchFile docs

docs/space-daemon/getting-started.md
=> Fix searchFiles docs

docs/space-daemon/getting-started.md
=> Updated subscribe docs

docs/space-daemon/crypto.md, docs/space-daemon/overview.md, mkdocs.yml
Also includes some small improvements to the overview section.
=> Add crypto and security docs for Space Daemon

docs/space-daemon/getting-started.md
=> update fuse docs

docs/space-desktop/overview.md, mkdocs.yml
Link to Space Desktop doc: https://bafybeieywpftzgz24x2pauuje3fidko3iyjuepwjux3ln6aa43o3zcbe7y.on.fleek.co/space-desktop/overview/
=> Add space desktop section

docs/space-daemon/reset-env.md, mkdocs.yml
=> Added reset env docs

docs/hosting/domain-management.md, docs/index.md, docs/space-daemon/getting-started.md, docs/storage/fleek-storage-js.md, docs/storage/storage-app.md, docs/storage/storage-aws-s3-integration.md
I fixed some small typo errors in docs.
=> fix: small errors

docs/storage/custom-storage-domains.md, docs/storage/overview.md, mkdocs.yml
Added new section to menu, linked in docs, and changed final url.
=> Menu + url

docs/domain-management/ens-domains.md
Updated the ENS unwrapping docs
https://support.ens.domains/en/articles/8031888-unwrapping-names
=> Update ens unwrapping docs

README.md, docs/index.md, docs/storage/overview.md, mkdocs.yml
=> Change /fleekxyz to /fleek
